package activity

const (
	ActivityProjectCreated                = "project.created"
	ActivityProjectArchived               = "project.archived"
	ActivityProjectCompleted              = "project.completed"
	ActivityProjectStatusChanged          = "project.status_changed"
	ActivityProjectUpdated                = "project.updated"
	ActivityProjectClientAssigned         = "project.client_assigned"
	ActivityProjectClientRemoved          = "project.client_removed"
	ActivityMilestoneCreated              = "milestone.created"
	ActivityMilestoneStarted              = "milestone.started"
	ActivityMilestoneCompleted            = "milestone.completed"
	ActivityMilestoneCancelled            = "milestone.cancelled"
	ActivityMilestoneStatusChanged        = "milestone.status_changed"
	ActivityMilestoneUpdated              = "milestone.updated"
	ActivityMilestoneSubmitted            = "milestone.submitted"
	ActivityMilestoneApproved             = "milestone.approved"
	ActivityMilestoneChangesRequested     = "milestone.changes_requested"
	ActivityMilestonePaymentStatusChanged = "milestone.payment_status_changed"
	ActivityAssignmentCreated             = "assignment.created"
	ActivityAssignmentUpdated             = "assignment.updated"
	ActivityAssignmentRemoved             = "assignment.removed"
	ActivityClientProvisioned             = "client.provisioned"
	ActivityClientCredentialRotated       = "client.credential_rotated"
	ActivityDeliverableSubmitted          = "deliverable.submitted"
	ActivityDeliverableRemoved            = "deliverable.removed"
	ActivityProjectRevisionLimitChanged   = "project.revision_limit_changed"
	ActivityMilestoneRevisionLimitChanged = "milestone.revision_limit_changed"
	ActivityProjectDeleted                = "project.deleted"
	ActivityProjectRestored               = "project.restored"
)
